const:
  - &max_N 5
  - &size_D 10
  - &size_H 5

components:
  history:
    class_name: tc.nn.LSTM
    params:
      input_size: 100
      hidden_size: 5
    output: x_g
  interactions:
    class_name: tc.nn.LSTM
    params:
      input_size: 12
      hidden_size: 6
    inputs:
      - x_t
      - y_t
    output: x_f

mapping:
  - [lstm_32, lstm_8]
  - [lstm_32, CELU, attn]